[build]
  base = "chesa-stock-exchange/frontend"
  command = "CI=false npm install && CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
